# Generated by Django 4.2.20 on 2025-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptchaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("captcha", models.TextField(max_length=4)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
