# Generated by Django 4.2.20 on 2025-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
